panicDeck = ds_list_create()

for(i = 0; i < 40; i++)
{
	panicArray[i] = instance_create_depth(-1000,-1000,0,obj_panicCard)
	ds_list_add(panicDeck,panicArray[i])
}

crd = 0

#region //1-40 Universal
definePanicCard("SICK","If Nauseous\n \n Fall to your knees vomiting, becoming helpless and suffering Weakness 1.\n Roll Health each upkeep to recover from helplessness. \n \n ELSE \n \n Become Nauseous")
definePanicCard("SICK","If Nauseous\n \n Fall to your knees vomiting, becoming helpless and suffering Weakness 1.\n Roll Health each upkeep to recover from helplessness. \n \n ELSE \n \n Become Nauseous")
definePanicCard("SICK","If Nauseous\n \n Fall to your knees vomiting, becoming helpless and suffering Weakness 1.\n Roll Health each upkeep to recover from helplessness. \n \n ELSE \n \n Become Nauseous")
definePanicCard("SICK","If Nauseous\n \n Fall to your knees vomiting, becoming helpless and suffering Weakness 1.\n Roll Health each upkeep to recover from helplessness. \n \n ELSE \n \n Become Nauseous")
definePanicCard("FROZEN","Freeze completely, dropping any items in hand and becoming helpless.\n Roll Morale each upkeep to recover from helplessness.")
definePanicCard("FROZEN","Freeze completely, dropping any items in hand and becoming helpless.\n Roll Morale each upkeep to recover from helplessness.")
definePanicCard("STARTLED","Lose all remaining action points.")
definePanicCard("STARTLED","Lose all remaining action points.")
definePanicCard("SHATTERED","If Stressed\n \n You cry, scream, and/or writhe uncontrollably for 1d5 rounds. \n \n ELSE \n \n Lose all remaining action points.")
definePanicCard("SHATTERED","If Stressed\n \n You cry, scream, and/or writhe uncontrollably for 1d5 rounds. \n \n ELSE \n \n Lose all remaining action points.")
definePanicCard("FAINT","Roll a Health check, falling unconscious for 1d5 minutes on a faiure and suffering Weakness 1 regardless of success.")
definePanicCard("FAINT","Roll a Health check, falling unconscious for 1d5 minutes on a faiure and suffering Weakness 1 regardless of success.")
definePanicCard("SNAP","Roll a Health check, falling unconscious for 1d5 hours on a faiure and suffering Weakness 1 regardless of success.")
definePanicCard("SNAP","Roll a Health check, falling unconscious for 1d5 hours on a faiure and suffering Weakness 1 regardless of success.")
definePanicCard("SHOCK","Roll a Health and Morale check, falling unconscious for 1d5 hours if you fail both... \n \n Also your heart stops.")
definePanicCard("SAVE YOURSELF","If you are surrounded\n \n Become Bloodthirsty and Bold. \n \n ELSE \n \n You cannot take attack actions for 1d5 rounds.")
definePanicCard("SAVE YOURSELF","If you are surrounded\n \n Become Bloodthirsty and Bold. \n \n ELSE \n \n You cannot take attack actions for 1d5 rounds.")
definePanicCard("SAVE YOURSELF","If you are surrounded\n \n Become Bloodthirsty and Bold. \n \n ELSE \n \n You cannot take attack actions for 1d5 rounds.")
definePanicCard("SAVE YOURSELF","If you are surrounded\n \n Become Bloodthirsty and Bold. \n \n ELSE \n \n You cannot take attack actions for 1d5 rounds.")
definePanicCard("SAVE YOURSELF","If you are surrounded\n \n Become Bloodthirsty and Bold. \n \n ELSE \n \n You cannot take attack actions for 1d5 rounds.")
definePanicCard("FLASHBACK","RECALL Memory 1.")
definePanicCard("FLASHBACK","RECALL Memory 2.")
definePanicCard("FLASHBACK","RECALL Memory 3.")
definePanicCard("FLASHBACK","RECALL Memory 4.")
definePanicCard("FLASHBACK","RECALL Memory 5.")
definePanicCard("FLASHBACK","RECALL Memory 6.")
definePanicCard("FLASHBACK","RECALL Memory 7.")
definePanicCard("FLASHBACK","RECALL Memory 8.")
definePanicCard("FLASHBACK","RECALL Memory 9.")
definePanicCard("FLASHBACK","RECALL Memory 10.")
definePanicCard("FLASHBACK","RECALL Memory 11.")
definePanicCard("FLASHBACK","RECALL Memory 12.")
definePanicCard("FLASHBACK","RECALL Memory 13.")
definePanicCard("FLASHBACK","RECALL Memory 14.")
definePanicCard("FLASHBACK","RECALL Memory 15.")
definePanicCard("FLASHBACK","RECALL Memory 16.")
definePanicCard("FLASHBACK","RECALL Memory 17.")
definePanicCard("FLASHBACK","RECALL Memory 18.")
definePanicCard("FLASHBACK","RECALL Memory 19.")
definePanicCard("FLASHBACK","RECALL Memory 20.")
#endregion